[package]
name = "arc180"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
rand = "*"
itertools = "*"
proconio = "*"
ac-library-rs = "*"

[profile.release]
lto = true
panic = 'abort'
